name: Build iOS IPA with Theos
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Theos and SDK
      run: |
        git clone --recursive https://github.com/theos/theos.git ~/theos
        git clone --depth=1 https://github.com/xybp888/iOS-SDKs.git ~/theos/sdks/iOS-SDKs
        mv ~/theos/sdks/iOS-SDKs/*.sdk ~/theos/sdks/
        rm -rf ~/theos/sdks/iOS-SDKs
        echo "THEOS=~/theos" >> $GITHUB_ENV

    - name: Unzip Source Code
      run: |
        unzip Fakelagapp.zip -d .

    - name: Compile Application
      run: |
        export THEOS=~/theos
        make package FINALPACKAGE=1

    - name: Create Payload and IPA
      run: |
        mkdir -p Payload
        cp -r .theos/obj/FakeLagApp.app Payload/
        zip -vr FakeLagApp.ipa Payload/

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v3
      with:
        name: FakeLagApp-IPA
        path: FakeLagApp.ipa
